name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: TarradeMarc
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/tarrardemarc/myapp:latest
       docker run ghcr.io/tarrademarc/myapp:latest
       docker push ghcr.io/tarrademarc/myapp:latest