name: publish
on: [push]
jobs:
	myapp:
  	runs-on: ubuntu-latest
  	steps:
    	- uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
      	uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
	  	- name: Build the hello-docker Docker image
	    	run: |
	      	docker build . --tag ghcr.io/tarrademarc/myapp:latest
	      	docker run ghcr.io/tarrademarc/myapp:latest
  	      docker push ghcr.io/tarrademarc/myapp:latest
